name: Build Windows Executable

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Actualizado a la versión 3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Cambia esto si usas otra versión

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Si no tienes dependencias, puedes eliminar esta línea.

      - name: Build executable
        run: pyinstaller --onefile --distpath . felizDia.py  # Cambia 'felizDia.py' por el nombre de tu archivo principal.

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # Actualizado a la versión 3
        with:
          name: Windows-executable
          path: felizDia.exe  # Aquí se guarda el ejecutable en la raíz
