name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --distpath . florez-python.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-executable
          path: florez-python.exe
